/* =================== Concession Viktoria - script.js =================== */

// ---------------------- Liste des véhicules ----------------------
const VEHICLES = [
  { name: "Panto", price: 4500, category: "compacts" },
  { name: "Regina", price: 4500, category: "sedans" },
  { name: "Asbo", price: 6500, category: "compacts" },
  { name: "Ingot", price: 6500, category: "sedans" },
  { name: "Emperor Rouillée", price: 7000, category: "sedans" },
  { name: "Blista", price: 7500, category: "compacts" },
  { name: "Stratum", price: 7500, category: "sedans" },
  { name: "Asea", price: 8000, category: "sedans" },
  { name: "Arias", price: 8500, category: "compacts" },
  { name: "Rhapsody", price: 8500, category: "compacts" },
  { name: "Beater Emperor", price: 9000, category: "sedans" },
  { name: "Beater Voodoo", price: 9000, category: "muscle" },
  { name: "Blazer", price: 9000, category: "off-road" },
  { name: "Journey", price: 9000, category: "vans" },
  { name: "Prairie", price: 9500, category: "compacts" },
  { name: "Tornado Mariachi", price: 9500, category: "off-road" },
  { name: "Voodoo", price: 9700, category: "muscle" },
  { name: "Emperor", price: 10000, category: "sedans" },
  { name: "EVA", price: 10000, category: "compacts" },
  { name: "Blista Compact", price: 10500, category: "sport" },
  { name: "Dune Buggy", price: 10500, category: "off-road" },
  { name: "Primo", price: 10500, category: "sedans" },
  { name: "Warrener", price: 11000, category: "sedans" },
  { name: "Kalahari", price: 11200, category: "off-road" },
  { name: "Duneloader", price: 11500, category: "off-road" },
  { name: "Surfer 2", price: 11500, category: "vans" },
  { name: "Issi Classic", price: 11500, category: "compacts" },
  { name: "Washington", price: 11500, category: "sedans" },
  { name: "Intruder", price: 12000, category: "sedans" },
  { name: "Dilettante", price: 12500, category: "compacts" },
  { name: "Issi", price: 12500, category: "compacts" },
  { name: "Penman", price: 12500, category: "sport-classic" },
  { name: "Tulip M-100 Sedan", price: 12500, category: "sedans" },
  { name: "Stanier", price: 14500, category: "sedans" },
  { name: "Beater Tornado", price: 15000, category: "sport-classic" },
  { name: "Cheburek", price: 15000, category: "sport-classic" },
  { name: "Blista Compact Roadster", price: 15000, category: "sport" },
  { name: "Bodhi", price: 15000, category: "off-road" },
  { name: "Glendale", price: 15000, category: "sedans" },
  { name: "Vivant", price: 15000, category: "compacts" },
  { name: "Youga", price: 15000, category: "vans" },
  { name: "Premier", price: 15500, category: "sedans" },
  { name: "Buffalo", price: 16000, category: "sport" },
  { name: "Dynasty", price: 16000, category: "sport-classic" },
  { name: "Fagaloa", price: 16000, category: "sport-classic" },
  { name: "Stanier LE", price: 16000, category: "sedans" },
  { name: "Surfer", price: 16000, category: "vans" },
  { name: "Tornado", price: 16000, category: "sport-classic" },
  { name: "Phoenix", price: 16500, category: "muscle" },
  { name: "Vigero", price: 16500, category: "muscle" },
  { name: "Manana", price: 16800, category: "sport-classic" },
  { name: "Minivan", price: 17000, category: "vans" },
  { name: "Moonbeam", price: 17000, category: "vans" },
  { name: "Postlude", price: 17000, category: "coupe" },
  { name: "Fugitive", price: 17500, category: "sedans" },
  { name: "Castella", price: 18000, category: "compacts" },
  { name: "Fagaloa Coupe", price: 18000, category: "sport-classic" },
  { name: "Futo", price: 18000, category: "sport" },
  { name: "Virgo", price: 18000, category: "muscle" },
  { name: "Blista Kanjo", price: 18500, category: "compacts" },
  { name: "Youga Classic", price: 18500, category: "vans" },
  { name: "Mesa", price: 19000, category: "SUV" },
  { name: "Rumpo", price: 19000, category: "vans" },
  { name: "Speedo", price: 19000, category: "vans" },
  { name: "Weevil", price: 19000, category: "compacts" },
  { name: "Blade", price: 19000, category: "muscle" },
  { name: "Chino", price: 19000, category: "muscle" },
  { name: "Remorque à bateau", price: 19500, category: "remorques" },
  { name: "Stallion", price: 19500, category: "muscle" },
  { name: "Asterope", price: 20000, category: "sedans" },
  { name: "BF Injection", price: 20000, category: "off-road" },
  { name: "Eudora", price: 20000, category: "muscle" },
  { name: "Paradise", price: 20000, category: "vans" },
  { name: "Vorstand", price: 20000, category: "sport" },
  { name: "Zion", price: 20000, category: "coupe" },
  { name: "Beater Rat-Truck", price: 20500, category: "muscle" },
  { name: "Journey II", price: 21000, category: "vans" },
  { name: "Rat-Truck", price: 21000, category: "muscle" },
  { name: "Buccaneer", price: 22000, category: "muscle" },
  { name: "Kanjo SJ", price: 22000, category: "coupe" },
  { name: "Picador", price: 22000, category: "muscle" },
  { name: "Tampa", price: 22000, category: "muscle" },
  { name: "Tulip M-100", price: 22000, category: "muscle" },
  { name: "Fhantom", price: 22500, category: "SUV" },
  { name: "Nebula", price: 22500, category: "sport-classic" },
  { name: "Primo Custom", price: 22500, category: "sedans" },
  { name: "Urban", price: 22500, category: "compacts" },
  { name: "Broadway", price: 23000, category: "muscle" },
  { name: "Burrito", price: 23000, category: "vans" },
  { name: "Zion Cabrio", price: 23000, category: "coupe" },
  { name: "Buffalo S", price: 24000, category: "sport" },
  { name: "Faction", price: 24000, category: "muscle" },
  { name: "Pico", price: 24000, category: "compacts" },
  { name: "Pigalle", price: 24000, category: "sport-classic" },
  { name: "Surfer Custom", price: 24000, category: "vans" },
  { name: "Virgo Classic", price: 24000, category: "muscle" },
  { name: "Warrener HRK", price: 24000, category: "sedans" },
  { name: "Radius", price: 25000, category: "SUV" },
  { name: "Slam Van", price: 25000, category: "muscle" },
  { name: "Brioso 300", price: 25500, category: "sport-classic" },
  { name: "Penumbra", price: 25500, category: "sport" },
  { name: "Vamos", price: 25500, category: "muscle" },
  { name: "Habanero", price: 26500, category: "SUV" },
  { name: "Imperial", price: 26500, category: "vans" },
  { name: "Peyote", price: 26500, category: "sport-classic" },
  { name: "Sabre GT", price: 26500, category: "muscle" },
  { name: "Semiole", price: 26500, category: "SUV" },
  { name: "Tornado Custom", price: 26500, category: "sport-classic" },
  { name: "Sentinel XS", price: 26500, category: "coupe" },
  { name: "Chino Luxe", price: 27000, category: "muscle" },
  { name: "Surge", price: 27500, category: "sedans" },
  { name: "Buffalo Sprunk", price: 28500, category: "sport" },
  { name: "Imperial Passenger", price: 28500, category: "vans" },
  { name: "Primo Lx", price: 28500, category: "sedans" },
  { name: "Sentinel", price: 28500, category: "coupe" },
  { name: "Brisco R/A", price: 29000, category: "compacts" },
  { name: "Clique", price: 29000, category: "muscle" },
  { name: "Blazer Sport", price: 29500, category: "off-road" },
  { name: "Impaler", price: 29500, category: "muscle" },
  { name: "Minivan Custom", price: 29500, category: "vans" },
  { name: "Petite Remorque", price: 29500, category: "remorques" },
  { name: "Rancher XL", price: 29500, category: "off-road" },
  { name: "Recursion", price: 29500, category: "sport" },
  { name: "Youga Classic 4x4", price: 29500, category: "vans" },
  { name: "Esperanto", price: 29750, category: "sedans" },
  { name: "Asterope GZ", price: 30500, category: "sedans" },
  { name: "Buccaneer Rider", price: 30500, category: "muscle" },
  { name: "Dorado", price: 30500, category: "SUV" },
  { name: "Nebula Wagon", price: 30500, category: "sport-classic" },
  { name: "Pony Navarra", price: 30500, category: "vans" },
  { name: "Rebel Rouillé", price: 30500, category: "off-road" },
  { name: "Sultan", price: 30500, category: "sport" },
  { name: "Glendale Custom", price: 31000, category: "sedans" },
  { name: "Tahoma Coupe", price: 31500, category: "muscle" },
  { name: "Futo GTX", price: 32000, category: "sport" },
  { name: "Tailgater", price: 32000, category: "sedans" },
  { name: "Verus", price: 32000, category: "off-road" },
  { name: "Boor", price: 32500, category: "off-road" },
  { name: "Brisco 300 Widebody", price: 32500, category: "compacts" },
  { name: "Club", price: 32500, category: "compacts" },
  { name: "Dukes", price: 32500, category: "muscle" },
  { name: "Faction XL", price: 32500, category: "muscle" },
  { name: "Fusilade", price: 32500, category: "sport" },
  { name: "Huntley S", price: 32500, category: "SUV" },
  { name: "Moonbean Custom", price: 32500, category: "vans" },
  { name: "Penumbra FF", price: 32500, category: "sport" },
  { name: "Rumpo Trail", price: 32500, category: "vans" },
  { name: "Sabre Turbo", price: 32500, category: "muscle" },
  { name: "Scharmann", price: 32500, category: "sedans" },
  { name: "Serrano", price: 32500, category: "SUV" },
  { name: "Virgo Classic Custom", price: 32500, category: "muscle" },
  { name: "Clique Wagon", price: 33000, category: "muscle" },
  { name: "Tahoma", price: 33000, category: "sedans" },
  { name: "Tahoma Rouillée", price: 33000, category: "sedans" },
  { name: "Burrito", price: 33500, category: "vans" },
  { name: "Impaler LX", price: 33500, category: "muscle" },
  { name: "Issi Offroad", price: 33500, category: "off-road" },
  { name: "Pigalle MILORD", price: 33500, category: "sport-classic" },
  { name: "Schafter", price: 34000, category: "sedans" },
  { name: "Bobcat XL", price: 34500, category: "vans" },
  { name: "Caravane", price: 34500, category: "remorques" },
  { name: "Casco", price: 34500, category: "sport-classic" },
  { name: "Faction Rider", price: 34500, category: "muscle" },
  { name: "Gauntlet", price: 34500, category: "muscle" },
  { name: "Glendale Krieger Special", price: 34500, category: "sedans" },
  { name: "Manana Custom", price: 34500, category: "muscle" },
  { name: "Oracle XS", price: 34500, category: "coupe" },
  { name: "Rebel", price: 34500, category: "off-road" },
  { name: "Zodiac", price: 34500, category: "sport" },
  { name: "Bifta", price: 35500, category: "off-road" },
  { name: "Tulip", price: 35500, category: "muscle" },
  { name: "BeeJay XL", price: 36000, category: "SUV" },
  { name: "Impaler SZ", price: 36000, category: "sedans" },
  { name: "Imperial EV", price: 36000, category: "vans" },
  { name: "Schwartzer Classic", price: 36000, category: "coupe" },
  { name: "Tahoma GT", price: 36000, category: "muscle" },
  { name: "Zion Classic", price: 36000, category: "sport-classic" },
  { name: "Clique Deluxe", price: 37000, category: "sport-classic" },
  { name: "Coquette BlackFin", price: 37000, category: "muscle" },
  { name: "F620", price: 37000, category: "coupe" },
  { name: "Jackal", price: 37000, category: "coupe" },
  { name: "Oracle", price: 37000, category: "coupe" },
  { name: "XLS", price: 37000, category: "SUV" },
  { name: "Camion de ferrailleur", price: 37500, category: "vans" },
  { name: "Ruiner", price: 38000, category: "muscle" },
  { name: "Vivanite", price: 38000, category: "SUV" },
  { name: "Youga Custom", price: 38500, category: "vans" },
  { name: "Camper", price: 39000, category: "vans" },
  { name: "Cavalcade", price: 39000, category: "SUV" },
  { name: "Kuruma", price: 39000, category: "sport" },
  { name: "Rocoto", price: 39000, category: "SUV" },
  { name: "Weevil Custom", price: 39000, category: "muscle" },
  { name: "Brisco Fulmine", price: 40000, category: "compacts" },
  { name: "Buffalo A/C", price: 40000, category: "sport" },
  { name: "Dominator", price: 40000, category: "muscle" },
  { name: "Omnis", price: 40000, category: "sport" },
  { name: "Peyote Custom", price: 40000, category: "sport-classic" },
  { name: "Rumpo Esperta", price: 40000, category: "vans" },
  { name: "Yosemite", price: 40000, category: "muscle" },
  { name: "Asterope RS", price: 41000, category: "sport" },
  { name: "Landstalker", price: 41000, category: "SUV" },
  { name: "Penumbra Retro", price: 41000, category: "sport" },
  { name: "Seraph XS", price: 41000, category: "sedans" },
  { name: "Vigero Rumbler", price: 41000, category: "muscle" },
  { name: "Felon", price: 42000, category: "coupe" },
  { name: "Sigma-Two", price: 42000, category: "sport" },
  { name: "Freecrawler", price: 42500, category: "off-road" },
  { name: "Gresley", price: 42500, category: "SUV" },
  { name: "Semiole Frontier", price: 42500, category: "SUV" },
  { name: "Khamelion", price: 43000, category: "sport" },
  { name: "Mesa Trail", price: 43000, category: "off-road" },
  { name: "Ruiner ZZ-8", price: 43000, category: "muscle" },
  { name: "Cognoscenti", price: 43200, category: "sedans" },
  { name: "Schwartzer", price: 43500, category: "sport" },
  { name: "Felon GT", price: 44000, category: "coupe" },
  { name: "Ingot VD90R", price: 44000, category: "sedans" },
  { name: "Zodiac Camper", price: 44000, category: "sport" },
  { name: "A-Type", price: 45000, category: "sport-classic" },
  { name: "Bison", price: 45000, category: "vans" },
  { name: "Bison 3", price: 45000, category: "vans" },
  { name: "Deviant", price: 45000, category: "muscle" },
  { name: "Dominator Pibwasser", price: 45000, category: "muscle" },
  { name: "Feroci Custom", price: 45000, category: "sedans" },
  { name: "Lynx", price: 45000, category: "sport" },
  { name: "Raptor", price: 45000, category: "sport" },
  { name: "Sentinel SG3 SE Coupe", price: 45000, category: "coupe" },
  { name: "Sentinel SG3 SE Sedan", price: 45000, category: "sedans" },
  { name: "Tornado Rat Rod", price: 45000, category: "sport-classic" },
  { name: "Tropos", price: 45000, category: "sport" },
  { name: "Yosemite Drift", price: 45000, category: "muscle" },
  { name: "Boor Widebody", price: 46500, category: "sport" },
  { name: "Club Cabriolet", price: 46500, category: "compacts" },
  { name: "Hizoku", price: 46500, category: "off-road" },
  { name: "Rebel Service", price: 46500, category: "off-road" },
  { name: "Rebel Utilitaire", price: 46500, category: "off-road" },
  { name: "Ariant", price: 47000, category: "sport" },
  { name: "Schwartzer Classic STR", price: 47000, category: "coupe" },
  { name: "Sentinel SG4", price: 47000, category: "coupe" },
  { name: "Vigero Rumble Drag", price: 47000, category: "muscle" },
  { name: "Club GTR", price: 48000, category: "compacts" },
  { name: "Rapid GT", price: 48000, category: "sport" },
  { name: "Seraph XS V10", price: 48000, category: "sedans" },
  { name: "Hizoku Widebody", price: 48500, category: "off-road" },
  { name: "Peyote Gasser", price: 48500, category: "muscle" },
  { name: "Cavalcade II", price: 49000, category: "SUV" },
  { name: "Altior", price: 49500, category: "sedans" },
  { name: "Hotring Weevil", price: 50000, category: "compacts" },
  { name: "Oracle XS LWB", price: 50000, category: "coupe" },
  { name: "Walton L35", price: 50000, category: "off-road" },
  { name: "Beater Dukes", price: 51000, category: "muscle" },
  { name: "Brawler", price: 51000, category: "off-road" },
  { name: "Dominator GTX", price: 51000, category: "muscle" },
  { name: "Dubsta", price: 51000, category: "SUV" },
  { name: "Outlaw", price: 51000, category: "off-road" },
  { name: "Remus", price: 51000, category: "sport" },
  { name: "ZR-150", price: 51000, category: "sport-classic" },
  { name: "Ellie", price: 52000, category: "muscle" },
  { name: "Matador", price: 52000, category: "sport-classic" },
  { name: "Nightshade", price: 52000, category: "muscle" },
  { name: "Scheisser", price: 52000, category: "sedans" },
  { name: "Cognoscenti Cabrio", price: 52500, category: "coupe" },
  { name: "Zodiac LM", price: 53000, category: "sport" },
  { name: "KS Zion Classic", price: 54000, category: "sport-classic" },
  { name: "Spritzer STR", price: 54000, category: "sport" },
  { name: "Alpha", price: 55000, category: "sport" },
  { name: "Cognoscenti 55", price: 55000, category: "sedans" },
  { name: "Compact Wagon", price: 55500, category: "compacts" },
  { name: "Serena", price: 55500, category: "sport-classic" },
  { name: "Bison STX", price: 56000, category: "vans" },
  { name: "Chariot Kart", price: 56000, category: "sport" },
  { name: "Coquette Classic", price: 56000, category: "sport-classic" },
  { name: "Granger", price: 56000, category: "SUV" },
  { name: "Greenwood", price: 56000, category: "muscle" },
  { name: "JB 700", price: 56000, category: "sport-classic" },
  { name: "Mesos", price: 56000, category: "sport" },
  { name: "Peanut", price: 56000, category: "sport" },
  { name: "Sadler", price: 56000, category: "SUV" },
  { name: "Sandking", price: 56000, category: "off-road" },
  { name: "Surano", price: 56000, category: "sport" },
  { name: "Bestia GTS", price: 57500, category: "sport" },
  { name: "Elegy RH8", price: 57500, category: "sport" },
  { name: "Rapid GT Convertible", price: 57500, category: "sport" },
  { name: "Exemplar", price: 58000, category: "coupe" },
  { name: "JB 700W", price: 58000, category: "sport-classic" },
  { name: "Remus Cabrio", price: 58000, category: "sport" },
  { name: "Schrauber", price: 58000, category: "sport" },
  { name: "Vincent Sport", price: 59000, category: "sport" },
  { name: "Sigma-Three", price: 59500, category: "sport" },
  { name: "Baller", price: 60000, category: "SUV" },
  { name: "Sentinel Classic DTM", price: 60000, category: "sport" },
  { name: "Zion Classic LM", price: 60000, category: "sport-classic" },
  { name: "Indiana", price: 61000, category: "off-road" },
  { name: "Spritzer DTM", price: 61000, category: "sport" },
  { name: "Vincent Tourer", price: 61000, category: "sport" },
  { name: "Everon Stock", price: 62000, category: "off-road" },
  { name: "Patriot", price: 62000, category: "SUV" },
  { name: "ZR-250", price: 62000, category: "sport-classic" },
  { name: "Feltzer", price: 62500, category: "sport" },
  { name: "Furore GT", price: 62500, category: "sport" },
  { name: "Kawaii", price: 62500, category: "sport" },
  { name: "Massacro", price: 62500, category: "sport" },
  { name: "Sultan Classic", price: 62500, category: "sport" },
  { name: "Contender", price: 64000, category: "SUV" },
  { name: "FR36", price: 64000, category: "coupe" },
  { name: "Mesa R", price: 64500, category: "off-road" },
  { name: "Gresley Hellhound", price: 65000, category: "SUV" },
  { name: "Monroe", price: 65000, category: "sport-classic" },
  { name: "Banshee", price: 67000, category: "sport" },
  { name: "Coquette", price: 67000, category: "sport" },
  { name: "Dubsta Luxury", price: 67000, category: "SUV" },
  { name: "Gauntlet Classic", price: 67000, category: "muscle" },
  { name: "Nexus", price: 67000, category: "sport" },
  { name: "Previon", price: 67000, category: "berline" },
  { name: "S-230", price: 67000, category: "sport" },
  { name: "Trophy Truck", price: 67000, category: "truck" },
  { name: "Yosemite SWB", price: 67000, category: "SUV" },
  { name: "Hustler", price: 70500, category: "sport" },
  { name: "Aleutian", price: 72000, category: "SUV" },
  { name: "Guardian", price: 72000, category: "SUV" },
  { name: "Hellion", price: 72500, category: "truck" },
  { name: "Stinger", price: 72500, category: "sport" },
  { name: "Verlierer", price: 72500, category: "sport" },
  { name: "Yosemite Rancher", price: 72500, category: "SUV" },
  { name: "9F", price: 73000, category: "sport" },
  { name: "Indiana XL", price: 73000, category: "SUV" },
  { name: "Schafter LWB", price: 73000, category: "berline" },
  { name: "Comet", price: 75000, category: "sport" },
  { name: "Gauntlet Classic Custom", price: 75000, category: "muscle" },
  { name: "Hotknife", price: 75000, category: "muscle" },
  { name: "Oracle XS-LE", price: 75000, category: "berline" },
  { name: "Sandking XL", price: 75000, category: "truck" },
  { name: "Vagrant", price: 75000, category: "truck" },
  { name: "Windsor", price: 75000, category: "berline" },
  { name: "Riata S", price: 76000, category: "truck" },
  { name: "Coquette Phobos", price: 77500, category: "sport" },
  { name: "Riata TX", price: 79000, category: "truck" },
  { name: "Bandito", price: 80000, category: "SUV" },
  { name: "Gresley Hellhound", price: 80000, category: "SUV" },
  { name: "Gresley STX", price: 80000, category: "SUV" },
  { name: "Issy Sport", price: 80000, category: "compacte" },
  { name: "Mamba", price: 80000, category: "sport" },
  { name: "Molecule", price: 80000, category: "compacte" },
  { name: "Retinue", price: 80000, category: "berline" },
  { name: "MonstroCiti", price: 81000, category: "truck" },
  { name: "Scout", price: 81000, category: "truck" },
  { name: "Mark 1", price: 82000, category: "sport" },
  { name: "Caracara 2022", price: 82500, category: "truck" },
  { name: "Alamo 2600LS", price: 83000, category: "SUV" },
  { name: "Indiana XL Lifted", price: 83000, category: "SUV" },
  { name: "Ratel", price: 84000, category: "truck" },
  { name: "Remus II", price: 84000, category: "sport" },
  { name: "9F Cabrio", price: 85000, category: "sport" },
  { name: "Arbiter GT", price: 85000, category: "sport" },
  { name: "Baller II", price: 85000, category: "SUV" },
  { name: "Carbonizzare", price: 85000, category: "sport" },
  { name: "Executioner Classic", price: 85000, category: "muscle" },
  { name: "Jester", price: 85000, category: "sport" },
  { name: "Riata", price: 85000, category: "truck" },
  { name: "Roosevelt", price: 85000, category: "berline" },
  { name: "RV Caracara", price: 85000, category: "vans" },
  { name: "Schafter V12", price: 85000, category: "berline" },
  { name: "Stinger GT", price: 85000, category: "sport" },
  { name: "Seven 70", price: 87500, category: "sport" },
  { name: "Stirling GT", price: 87500, category: "sport" },
  { name: "Banshee Phase One", price: 90000, category: "sport" },
  { name: "Buggy Raid", price: 90000, category: "truck" },
  { name: "Dominator GTT", price: 90000, category: "muscle" },
  { name: "Brisket", price: 91000, category: "truck" },
  { name: "Jester Classic", price: 92500, category: "sport" },
  { name: "Komoda GT", price: 94000, category: "sport" },
  { name: "Sapphire", price: 94000, category: "sport" },
  { name: "Dominator GTX 2024", price: 95000, category: "muscle" },
  { name: "RV Sand Roamer", price: 95000, category: "vans" },
  { name: "Vesper", price: 95000, category: "sport" },
  { name: "Woodlander", price: 95000, category: "SUV" },
  { name: "Brisket Gasse", price: 96000, category: "truck" },
  { name: "Brisket Rally", price: 96000, category: "truck" },
  { name: "Paradox", price: 96500, category: "sport" },
  { name: "Picador EXR", price: 97500, category: "truck" },
  { name: "Retinue Mk II", price: 97500, category: "berline" },
  { name: "Savestra", price: 97500, category: "sport" },
  { name: "Caracara 4x4", price: 100000, category: "truck" },
  { name: "Dubsta 2022", price: 100000, category: "SUV" },
  { name: "Sidewinder", price: 100000, category: "sport" },
  { name: "Ardent", price: 105000, category: "sport" },
  { name: "Jester(Racecar)", price: 105000, category: "sport" },
  { name: "Vigero VL1/690SS", price: 105000, category: "sport" },
  { name: "Comet Safari", price: 107500, category: "sport" },
  { name: "Firebolt ASP", price: 107500, category: "sport" },
  { name: "Iris Z", price: 107500, category: "sport" },
  { name: "Krieger BPX-32B", price: 107500, category: "sport" },
  { name: "Landstalker XL", price: 107500, category: "SUV" },
  { name: "RT3000", price: 107500, category: "sport" },
  { name: "Stafford", price: 107500, category: "berline" },
  { name: "Sugoi", price: 107500, category: "sport" },
  { name: "ZR300", price: 107500, category: "sport" },
  { name: "Paradox Rally", price: 109000, category: "sport" },
  { name: "Issi Rally", price: 110000, category: "compacte" },
  { name: "Bison HF", price: 112500, category: "truck" },
  { name: "Comet SR", price: 112500, category: "sport" },
  { name: "Elegy RH4", price: 112500, category: "sport" },
  { name: "Euros", price: 112500, category: "sport" },
  { name: "Gauntlet Hellfire", price: 112500, category: "muscle" },
  { name: "Granger 3600LX", price: 112500, category: "SUV" },
  { name: "Hachura", price: 112500, category: "sport" },
  { name: "Hermes", price: 112500, category: "sport" },
  { name: "Michelli GT", price: 112500, category: "sport" },
  { name: "Novak", price: 112500, category: "sport" },
  { name: "Roosevelt Valor", price: 112500, category: "berline" },
  { name: "Sentinel Classic", price: 112500, category: "berline" },
  { name: "Specter", price: 112500, category: "sport" },
  { name: "RV Guardian", price: 112500, category: "vans" },
  { name: "Windsor Drop 2 Doors", price: 112500, category: "berline" },
  { name: "Massacro(Racecar)", price: 115500, category: "sport" },
  { name: "Razor", price: 119000, category: "muscle" },
  { name: "Surano E-Motion", price: 120000, category: "sport" },
  { name: "Rapid GT3", price: 122000, category: "sport" },
  { name: "Club XR", price: 122500, category: "sport" },
  { name: "Dominator GSX", price: 122500, category: "muscle" },
  { name: "RV Sandking", price: 122500, category: "vans" },
  { name: "Sancy B4", price: 122500, category: "sport" },
  { name: "Sultan RS Classic", price: 122500, category: "berline" },
  { name: "Windsor Drop", price: 122500, category: "berline" },
  { name: "ZR350", price: 122500, category: "sport" },
  { name: "Baller Sport", price: 125000, category: "SUV" },
  { name: "Coquette Thunderstruck", price: 125000, category: "sport" },
  { name: "Specter Custom", price: 125200, category: "sport" },
  { name: "Imorgon", price: 125600, category: "sport" },
  { name: "Super Diamond", price: 127500, category: "berline" },
  { name: "V-STR", price: 127500, category: "sport" },
  { name: "Vigero ZX", price: 127500, category: "sport" },
  { name: "Specter", price: 112500, category: "sport" },
  { name: "Windsor Drop 2 Doors", price: 112500, category: "berline" },
  { name: "Massacro(Racecar)", price: 115500, category: "sport" },
  { name: "Razor", price: 112500, category: "sport" },
  { name: "Surano E-Motion", price: 120000, category: "sport" },
  { name: "Rapid GT3", price: 122000, category: "sport" },
  { name: "Club XR", price: 122500, category: "sport" },
  { name: "Dominator GSX", price: 122500, category: "muscle" },
  { name: "Sancy B4", price: 122500, category: "sport" },
  { name: "Sultan RS Classic", price: 122500, category: "berline" },
  { name: "Windsor Drop", price: 122500, category: "berline" },
  { name: "ZR350", price: 122500, category: "sport" },
  { name: "Baller Sport", price: 125000, category: "SUV" },
  { name: "Coquette Thunderstruck", price: 125000, category: "sport" },
  { name: "Specter Custom", price: 125200, category: "sport" },
  { name: "Imorgon", price: 125600, category: "sport" },
  { name: "Super Diamond", price: 127500, category: "berline" },
  { name: "V-STR", price: 127500, category: "sport" },
  { name: "Vigero ZX", price: 127500, category: "sport" },
  { name: "300R", price: 130500, category: "sport" },
  { name: "Vulture", price: 131500, category: "muscle" },
  { name: "8F Drafter", price: 132500, category: "sport" },
  { name: "Elegy Retro Ute", price: 132500, category: "sport" },
  { name: "Elegy Retro Custom", price: 132500, category: "sport" },
  { name: "Hotring Everon", price: 132500, category: "sport" },
  { name: "Hotring Sabre", price: 132500, category: "sport" },
  { name: "Ruston", price: 132500, category: "sport" },
  { name: "Meteor", price: 133500, category: "sport" },
  { name: "Argento", price: 134500, category: "sedans" },
  { name: "Streiter Break", price: 134500, category: "SUV" },
  { name: "Dominator ASP", price: 135000, category: "muscle" },
  { name: "Cheetah Classic", price: 135000, category: "sport-classic" },
  { name: "Tailgater S", price: 135200, category: "sport" },
  { name: "Sultan Classic Rally", price: 136500, category: "sport" },
  { name: "Comet Retro Custom", price: 137500, category: "sport" },
  { name: "Sentinel Classic Custom", price: 137500, category: "sport" },
  { name: "Sultan RS", price: 137500, category: "super" },
  { name: "Sultan RS Ute", price: 137500, category: "super" },
  { name: "Vigero ZX Convertible", price: 137500, category: "muscle" },
  { name: "Z190", price: 137500, category: "sport" },
  { name: "Coquette D5", price: 138500, category: "sport" },
  { name: "Cheetah Veloce", price: 140000, category: "sport" },
  { name: "LSCM Cheetah Classic", price: 140500, category: "sport" },
  { name: "Elegy RH5", price: 141500, category: "sport" },
  { name: "Everon", price: 142500, category: "sport" },
  { name: "Locust", price: 142500, category: "sport" },
  { name: "Paragon R", price: 142500, category: "sport" },
  { name: "Torero", price: 142500, category: "sport" },
  { name: "Elegy RH6", price: 143500, category: "sport" },
  { name: "Baller LWB", price: 145000, category: "SUV" },
  { name: "Dubsta 6x6", price: 145000, category: "SUV" },
  { name: "Tampa Drift", price: 145000, category: "sport" },
  { name: "Turismo Classic", price: 145600, category: "sport" },
  { name: "Super GTS", price: 146500, category: "sport" },
  { name: "Cheetah Veloce Widebody", price: 147500, category: "sport" },
  { name: "Elegy RH7", price: 147500, category: "sport" },
  { name: "Rhinehart", price: 147500, category: "sport" },
  { name: "Sabot", price: 147500, category: "muscle" },
  { name: "Sentinel Classic Widebody", price: 147500, category: "berline" },
  { name: "Mantis", price: 148500, category: "sport" },
  { name: "Deimos", price: 150000, category: "sport" },
  { name: "Banshee S", price: 152500, category: "sport" },
  { name: "Z-Type", price: 152500, category: "sport" },
  { name: "Pariah", price: 154000, category: "sport" },
  { name: "Comet Retro", price: 155000, category: "sport" },
  { name: "GT 500", price: 155000, category: "sport" },
  { name: "Sultan Classic Custom", price: 157500, category: "berline" },
  { name: "Comet Callista", price: 160000, category: "sport" },
  { name: "Banshee GTS", price: 162500, category: "sport" },
  { name: "Castigator", price: 162500, category: "sport" },
  { name: "Streiter 4x4", price: 162500, category: "truck" },
  { name: "Bullet", price: 165000, category: "sport" },
  { name: "Infernus Classic", price: 165000, category: "sport" },
  { name: "GB200", price: 165200, category: "sport" },
  { name: "Solace", price: 166500, category: "sport" },
  { name: "Comet Classic", price: 167500, category: "sport-classic" },
  { name: "Sunrise R", price: 167500, category: "sport" },
  { name: "Nexus RR", price: 170500, category: "sport" },
  { name: "Turismo 3000GT", price: 170500, category: "sport" },
  { name: "Banshee 900R", price: 172500, category: "sport" },
  { name: "Dominator GT", price: 172500, category: "muscle" },
  { name: "Everon RS", price: 172500, category: "sport" },
  { name: "Flash GT", price: 172500, category: "sport" },
  { name: "Infernus", price: 172500, category: "sport" },
  { name: "Raiden", price: 172500, category: "sport" },
  { name: "Viseris", price: 172500, category: "sport" },
  { name: "Voltic", price: 172500, category: "sport" },
  { name: "Cypher", price: 175000, category: "sport" },
  { name: "Deity", price: 175000, category: "sport" },
  { name: "Swinger", price: 175000, category: "muscle" },
  { name: "Turismo 300GT Spider", price: 177500, category: "sport" },
  { name: "Solace Vitesse", price: 180500, category: "sport" },
  { name: "Turismo", price: 182500, category: "sport" },
  { name: "Calico GTF", price: 185000, category: "sport" },
  { name: "Hotring Hellfire", price: 187500, category: "sport" },
  { name: "Buffalo STX", price: 192500, category: "sport" },
  { name: "Bullet GT", price: 192500, category: "sport" },
  { name: "Cypher Hatchback", price: 192500, category: "sport" },
  { name: "Jester RR", price: 195000, category: "sport" },
  { name: "Toros", price: 195200, category: "truck" },
  { name: "Expression", price: 197500, category: "berline" },
  { name: "Panthere", price: 197500, category: "sport" },
  { name: "Mogul RS", price: 200500, category: "truck" },
  { name: "Baller ST-D", price: 202500, category: "SUV" },
  { name: "Buffalo EVX", price: 202500, category: "sport" },
  { name: "LSCM Jester RR", price: 202500, category: "sport" },
  { name: "Sentinel GTS", price: 202500, category: "berline" },
  { name: "SM722", price: 202500, category: "sport" },
  { name: "Vertice", price: 202500, category: "sport" },
  { name: "S95", price: 204500, category: "sport" },
  { name: "Eon", price: 207500, category: "sport" },
  { name: "Baller ST", price: 212500, category: "SUV" },
  { name: "Champion", price: 212500, category: "sport" },
  { name: "Cheetah", price: 212500, category: "sport" },
  { name: "Growler", price: 212500, category: "sport" },
  { name: "I-Wagen", price: 212500, category: "berline" },
  { name: "Patriot Stretch", price: 212500, category: "SUV" },
  { name: "Rebla GTS", price: 212500, category: "sport" },
  { name: "Vectre", price: 212500, category: "berline" },
  { name: "Rapid GT X", price: 220000, category: "sport" },
  { name: "Tannen", price: 222500, category: "sport" },
  { name: "Comet S1 Turbo", price: 225000, category: "sport" },
  { name: "Neon", price: 225000, category: "sport" },
  { name: "Nero", price: 235000, category: "sport" },
  { name: "Sandstorm D205", price: 235000, category: "truck" },
  { name: "Starlight", price: 235000, category: "sport" },
  { name: "Vacca", price: 235000, category: "sport" },
  { name: "Cavalcade XL", price: 245000, category: "SUV" },
  { name: "Cyclone", price: 245000, category: "sport" },
  { name: "Tannen Sport", price: 245000, category: "sport" },
  { name: "Celeste", price: 252500, category: "sport" },
  { name: "Sandstorm D205 Hellenbach", price: 252500, category: "truck" },
  { name: "Baller Raid", price: 255000, category: "SUV" },
  { name: "Sheava", price: 255000, category: "sport" },
  { name: "Sultan RSx", price: 255000, category: "berline" },
  { name: "Astron", price: 265000, category: "sport" },
  { name: "Comet S2", price: 265000, category: "sport" },
  { name: "Itali GTB", price: 265000, category: "sport" },
  { name: "Revolter", price: 265000, category: "sport" },
  { name: "Sandstorm D205 XL", price: 265000, category: "truck" },
  { name: "Penetrator", price: 270000, category: "sport" },
  { name: "Kamacho", price: 272500, category: "SUV" },
  { name: "Komoda", price: 275500, category: "sport" },
  { name: "La Coureuse", price: 285000, category: "sport" },
  { name: "Tempesta", price: 290000, category: "sport" },
  { name: "Entity XF", price: 292500, category: "sport" },
  { name: "Adder", price: 295000, category: "sport" },
  { name: "Itali GTB Custom", price: 295000, category: "sport" },
  { name: "Neo", price: 295000, category: "sport" },
  { name: "Schlagen GT", price: 295000, category: "sport" },
  { name: "Schlagen Roadster", price: 295000, category: "sport" },
  { name: "Schlagen SP", price: 295000, category: "sport" },
  { name: "Itali GTO Stinger TT", price: 300000, category: "sport" },
  { name: "Tempesta Spyder", price: 300000, category: "sport" },
  { name: "Astron Custom", price: 305000, category: "sport" },
  { name: "Neon CT", price: 305000, category: "sport" },
  { name: "Coquette D10", price: 310000, category: "sport" },
  { name: "Tigon", price: 207500, category: "sport" },
  { name: "Turismo R", price: 312500, category: "sport" },
  { name: "Schwartzer S", price: 315000, category: "sport" },
  { name: "Torexo XO", price: 315000, category: "sport" },
  { name: "811", price: 325000, category: "sport" },
  { name: "Cinquemilla", price: 325000, category: "sport" },
  { name: "Comet S2 cabrio", price: 325000, category: "sport" },
  { name: "FMJ", price: 325000, category: "sport" },
  { name: "Jubilee", price: 325000, category: "sport" },
  { name: "Reaper", price: 325000, category: "sport" },
  { name: "10F", price: 330000, category: "sport" },
  { name: "10F Widebody", price: 330000, category: "sport" },
  { name: "Cyclone II", price: 330000, category: "sport" },
  { name: "Paragon S", price: 335000, category: "sport" },
  { name: "SC 1", price: 335000, category: "sport" },
  { name: "MF1 Spyder", price: 340000, category: "sport" },
  { name: "Nero Custom", price: 340000, category: "sport" },
  { name: "Envisage", price: 342500, category: "sport" },
  { name: "ETR1", price: 345000, category: "sport" },
  { name: "XA-21", price: 345200, category: "sport" },
  { name: "Quantum", price: 350000, category: "sport" },
  { name: "10F Spyder", price: 355000, category: "sport" },
  { name: "Autarch", price: 360000, category: "sport" },
  { name: "Itali GTO", price: 365000, category: "sport" },
  { name: "GP1", price: 370000, category: "sport" },
  { name: "Jugular E", price: 370000, category: "sport" },
  { name: "Itali GTS", price: 375000, category: "sport" },
  { name: "Super Diamond S", price: 375000, category: "berline" },
  { name: "Corsita", price: 380000, category: "sport" },
  { name: "Suzume", price: 380000, category: "sport" },
  { name: "Jugular", price: 395000, category: "sport" },
  { name: "T20", price: 395000, category: "sport" },
  { name: "Nero Pur Sport", price: 400000, category: "sport" },
  { name: "Entity XXR", price: 405000, category: "sport" },
  { name: "Zentorno", price: 405000, category: "sport" },
  { name: "Osiris", price: 410000, category: "sport" },
  { name: "Visione", price: 412000, category: "sport" },
  { name: "Cyclone Ex-Zero", price: 420000, category: "sport" },
  { name: "Draugur", price: 420000, category: "sport" },
  { name: "Furia", price: 430000, category: "sport" },
  { name: "Taipan", price: 430000, category: "sport" },
  { name: "Tyrant", price: 430000, category: "sport" },
  { name: "Ronin", price: 435000, category: "sport" },
  { name: "Tyrus", price: 435000, category: "sport" },
  { name: "Emerus", price: 445000, category: "sport" },
  { name: "Schlagen STR", price: 445000, category: "sport" },
  { name: "Entity MT", price: 450000, category: "sport" },
  { name: "Itali GTO N-Larga", price: 465000, category: "sport" },
  { name: "Vagner", price: 472500, category: "sport" },
  { name: "Omnis e-GT", price: 475000, category: "sport" },
  { name: "Itali GTR", price: 485000, category: "sport" },
  { name: "Pipistrello", price: 485000, category: "sport" },
  { name: "Milano GTS", price: 495000, category: "sport" },
  { name: "Itali RSX", price: 525000, category: "sport" },
  { name: "Terminus", price: 525000, category: "sport" },
  { name: "Tezeract", price: 525000, category: "sport" },
  { name: "Audace", price: 530000, category: "sport" },
  { name: "Speedster", price: 550000, category: "sport" },
  { name: "Zorrusso", price: 575000, category: "sport" },
  { name: "X80 Proto", price: 585000, category: "sport" },
  { name: "Zeno", price: 585000, category: "sport" },
  { name: "S80RR", price: 600000, category: "sport" },
  { name: "RE-7B", price: 622500, category: "sport" },
  { name: "Krieger", price: 625000, category: "sport" },
  { name: "Niobe", price: 625000, category: "sport" },
  { name: "Deveste Eight", price: 630000, category: "sport" },
  { name: "LM87", price: 650000, category: "sport" },
  { name: "Majima GT", price: 665000, category: "sport" },
  { name: "Argento 7F", price: 810000, category: "sport" },
  { name: "Virtue", price: 860000, category: "sport" },
  { name: "FMJ GTE", price: 960000, category: "sport" },
  { name: "811 S2", price: 1010000, category: "sport" },
  { name: "Patriot Mil-Spec", price: 1010000, category: "SUV" },
  { name: "Harmann", price: 1060000, category: "sport" },
  { name: "Ignus", price: 1060000, category: "sport" },
  { name: "Tempesta Evo Stradale", price: 1160000, category: "sport" },
  { name: "Thrax", price: 1212500, category: "sport" },
  { name: "Hurricane", price: 1260000, category: "sport" },
  { name: "Comet S2R", price: 1960000, category: "sport" },
  { name: "Nero Supersport MK.II", price: 2060000, category: "sport" },
  { name: "Comet S2R Cabriolet", price: 2260000, category: "sport" },
  { name: "Turismo S", price: 2560000, category: "sport" },
  { name: "LOD-4", price: 5060000, category: "truck" },
  { name: "Zentorno CTX", price: 6100000, category: "sport" },
  { name: "Turismo Omaggio", price: 7100000, category: "sport" },
  { name: "Prospero", price: 7600000, category: "sport" },
  { name: "Ignus CTX", price: 8100000, category: "sport" },
  { name: "Emerus SB1", price: 8600000, category: "sport" },
  { name: "Ares GT", price: 9100000, category: "sport" },
  { name: "TR3-S", price: 10100000, category: "sport" },
  { name: "Tempesta Competizione Evo", price: 12100000, category: "sport" },
  { name: "Tula ( Avion )", price: 1900000, category: "avion" },
  { name: "Streamer216 X ( Avion )", price: 2000000, category: "avion" },
  { name: "Nimbus ( Avion )", price: 2500000, category: "avion" },
  { name: "Luxor ( Avion )", price: 2750000, category: "avion" },
  { name: "Luxor Deluxe ( Avion )", price: 3000000, category: "avion" },
  { name: "Shamal ( Avion )", price: 3250000, category: "avion" },
  { name: "Seashark SP ( Bateau )", price: 7500, category: "bateau" },
  { name: "Seashark SPX ( Bateau )", price: 7500, category: "bateau" },
  { name: "Wind Surf ( Bateau )", price: 8500, category: "bateau" },
  { name: "Pedalo ( Bateau )", price: 13500, category: "bateau" },
  { name: "Squalo ( Bateau )", price: 16000, category: "bateau" },
  { name: "Bateau Licorne ( Bateau )", price: 21500, category: "bateau" },
  { name: "Tropic ( Bateau )", price: 26500, category: "bateau" },
  { name: "Suntrap ( Bateau )", price: 47000, category: "bateau" },
  { name: "Dinghy 2 places ( Bateau )", price: 80000, category: "bateau" },
  { name: "Dinghy ( Bateau )", price: 135000, category: "bateau" },
  { name: "Jetmax ( Bateau )", price: 160000, category: "bateau" },
  { name: "Speeder ( Bateau )", price: 180000, category: "bateau" },
  { name: "Toro Yacht ( Bateau )", price: 245000, category: "bateau" },
  { name: "Toro ( Bateau )", price: 250000, category: "bateau" },
  { name: "Marquis ( Bateau )", price: 285000, category: "bateau" },
  { name: "Longfin ( Bateau )", price: 450000, category: "bateau" },
  { name: "Sea Ray 650 ( Bateau )", price: 600000, category: "bateau" },
  { name: "BMX ( Vélo )", price: 1660, category: "velo" },
  { name: "Fixter ( Vélo )", price: 1725, category: "velo" },
  { name: "Scorcher ( Vélo )", price: 1780, category: "velo" },
  { name: "Cruiser ( Vélo )", price: 2010, category: "velo" },
  { name: "Tri Bike ( Vélo )", price: 2020, category: "velo" },
  { name: "Inductor ( Vélo )", price: 2400, category: "velo" },
  { name: "Inductor Junk Energy ( Vélo )", price: 2400, category: "velo" },
  { name: "Frakas ( Moto )", price: 4000, category: "moto" },
  { name: "Rat Bike ( Moto )", price: 7000, category: "moto" },
  { name: "Manchez ( Moto )", price: 7500, category: "moto" },
  { name: "Sanchez Scout ( Moto )", price: 7500, category: "moto" },
  { name: "Nemesis ( Moto )", price: 8000, category: "moto" },
  { name: "Kuroi ( Moto )", price: 8500, category: "moto" },
  { name: "PCJ-600 ( Moto )", price: 8700, category: "moto" },
  { name: "Ruffian ( Moto )", price: 9300, category: "moto" },
  { name: "Vader ( Moto )", price: 9700, category: "moto" },
  { name: "Akuma ( Moto )", price: 10000, category: "moto" },
  { name: "Daemon ( Moto )", price: 10000, category: "moto" },
  { name: "Akuma Classic ( Moto )", price: 10500, category: "moto" },
  { name: "KTM EXC-F 250 ( Moto )", price: 11000, category: "moto" },
  { name: "Kunoichi ( Moto )", price: 11500, category: "moto" },
  { name: "Kusa ( Moto )", price: 12000, category: "moto" },
  { name: "Vortex ( Moto )", price: 12300, category: "moto" },
  { name: "Defiler ( Moto )", price: 12300, category: "moto" },
  { name: "Lectro ( Moto )", price: 12500, category: "moto" },
  { name: "FCR 1000 ( Moto )", price: 16000, category: "moto" },
  { name: "Wolfsbane ( Moto )", price: 16500, category: "moto" },
  { name: "Diabolus ( Moto )", price: 18000, category: "moto" },
  { name: "Wolfsbane 2 ( Moto )", price: 18000, category: "moto" },
  { name: "Bati 801 ( Moto )", price: 19000, category: "moto" },
  { name: "BF400 ( Moto )", price: 19000, category: "moto" },
  { name: "Bati 701 ( Moto )", price: 19000, category: "moto" },
  { name: "Hexer ( Moto )", price: 19000, category: "moto" },
  { name: "Sovereign ( Moto )", price: 20000, category: "moto" },
  { name: "Carbon RS ( Moto )", price: 22000, category: "moto" },
  { name: "Diabolus ( Moto biker )", price: 22000, category: "moto" },
  { name: "Kampfer ( Moto )", price: 22000, category: "moto" },
  { name: "Angel ( Moto )", price: 23000, category: "moto" },
  { name: "Freeway ( Moto )", price: 24000, category: "moto" },
  { name: "Manchez Scout ( Moto )", price: 24000, category: "moto" },
  { name: "FCR 1000 Custom ( Moto )", price: 25500, category: "moto" },
  { name: "Diabolus Custom ( Moto )", price: 26000, category: "moto" },
  { name: "Bati 801RR ( Moto )", price: 26500, category: "moto" },
  { name: "Bagger ( Moto )", price: 27000, category: "moto" },
  { name: "Thrust ( Moto )", price: 27500, category: "moto" },
  { name: "Avarus ( Moto )", price: 29500, category: "moto" },
  { name: "Manchez Scout C ( Moto )", price: 29500, category: "moto" },
  { name: "Templar ( Moto )", price: 31500, category: "moto" },
  { name: "Double T ( Moto )", price: 32500, category: "moto" },
  { name: "Wintergreen ( Moto )", price: 33000, category: "moto" },
  { name: "Bati 901 ( Moto )", price: 33500, category: "moto" },
  { name: "Cliffhanger ( Moto )", price: 34500, category: "moto" },
  { name: "Leviathan ( Moto )", price: 34500, category: "moto" },
  { name: "Sovereign 2 ( Moto )", price: 34500, category: "moto" },
  { name: "Vindicator ( Moto )", price: 34500, category: "moto" },
  { name: "Hakuchou ( Moto )", price: 36000, category: "moto" },
  { name: "Gargoyle ( Moto )", price: 40000, category: "moto" },
  { name: "Stryder ( Moto )", price: 40000, category: "moto" },
  { name: "SG1150 ( Moto )", price: 41000, category: "moto" },
  { name: "Revenant ( Moto )", price: 43000, category: "moto" },
  { name: "Double T Custom ( Moto )", price: 45000, category: "moto" },
  { name: "Honda CRF 450 ( Moto )", price: 45000, category: "moto" },
  { name: "Wayfarer ( Moto )", price: 45000, category: "moto" },
  { name: "Innovation ( Moto )", price: 46500, category: "moto" },
  { name: "YZ 450F ( Moto )", price: 48000, category: "moto" },
  { name: "Slave ( Moto )", price: 48500, category: "moto" },
  { name: "Hakuchou Sport ( Moto )", price: 51000, category: "moto" },
  { name: "Lycan Custom ( Moto )", price: 51000, category: "moto" },
  { name: "Zombie Bobber ( Moto )", price: 51000, category: "moto" },
  { name: "Santacruz ( Moto )", price: 54000, category: "moto" },
  { name: "Chimera ( Moto )", price: 56000, category: "moto" },
  { name: "Gyropode ( Moto )", price: 56000, category: "moto" },
  { name: "Hellfury ( Moto )", price: 56000, category: "moto" },
  { name: "Ventoso ( Moto )", price: 56000, category: "moto" },
  { name: "Zombie Chopper ( Moto )", price: 56000, category: "moto" },
  { name: "Reever ( Moto )", price: 62000, category: "moto" },
  { name: "Western Reever ( Moto )", price: 62000, category: "moto" },
  { name: "Nightblade ( Moto )", price: 67000, category: "moto" },
  { name: "Nightblade Classic ( Moto )", price: 71000, category: "moto" },
  { name: "Shinobi ( Moto )", price: 75000, category: "moto" },
  { name: "Slayer ( Moto )", price: 80000, category: "moto" },
  { name: "Shinobi Outlaw ( Moto )", price: 81000, category: "moto" },
  { name: "Ninja H2R ( Moto )", price: 82500, category: "moto" },
  { name: "BMW S1000 RR ( Moto )", price: 85000, category: "moto" },
  { name: "Nightblade Turbo ( Moto )", price: 85000, category: "moto" },
  { name: "Honda CBR 1000 RR ( Moto )", price: 87500, category: "moto" },
  { name: "Powersurge ( Moto )", price: 112500, category: "moto" },
  { name: "Sanctus ( Moto )", price: 152500, category: "moto" },
  { name: "Sidecar H ( Moto )", price: 192500, category: "moto" },
  { name: "6STR Gauntlet Custom ( Tunershop )", price: 254500, category: "tunershop" },
  { name: "6STR Tempesta Custom ( Tunershop )", price: 890000, category: "tunershop" },
  { name: "8F D Street ( Tunershop )", price: 397500, category: "tunershop" },
  { name: "Buffalo Hellhound ( Tunershop )", price: 204000, category: "tunershop" },
  { name: "Chilly Bin ( Tunershop )", price: 176000, category: "tunershop" },
  { name: "Contender Custom ( Tunershop )", price: 214000, category: "tunershop" },
  { name: "Coquette D10 Custom ( Tunershop )", price: 930000, category: "tunershop" },
  { name: "Elegy Zirconium Body Kit ( Tunershop )", price: 497500, category: "tunershop" },
  { name: "Elegy RH8 FRWorks ( Tunershop )", price: 437500, category: "tunershop" },
  { name: "Emperor GT ( Tunershop )", price: 220000, category: "tunershop" },
  { name: "Hachura R Custom ( Tunershop )", price: 685500, category: "tunershop" },
  { name: "Jackal Custom ( Tunershop )", price: 227000, category: "tunershop" },
  { name: "Jester MK4 Custom ( Tunershop )", price: 412500, category: "tunershop" },
  { name: "Jester Re-RR ( Tunershop )", price: 585000, category: "tunershop" },
  { name: "Kanjo R ( Tunershop )", price: 168500, category: "tunershop" },
  { name: "Komoda FRWorks ( Tunershop )", price: 835000, category: "tunershop" },
  { name: "Lynx Custom ( Tunershop )", price: 245000, category: "tunershop" },
  { name: "Monroe Custom ( Tunershop )", price: 250000, category: "tunershop" },
  { name: "Osiris FR-Works ( Tunershop )", price: 910000, category: "tunershop" },
  { name: "Panto R ( Tunershop )", price: 184500, category: "tunershop" },
  { name: "Playboy ( Tunershop )", price: 220500, category: "tunershop" },
  { name: "Paragon XR ( Tunershop )", price: 437500, category: "tunershop" },
  { name: "Paragon Offroad ( Tunershop )", price: 427500, category: "tunershop" },
  { name: "Quail V8 ( Tunershop )", price: 208500, category: "tunershop" },
  { name: "Rebel Raid ( Tunershop )", price: 169500, category: "tunershop" },
  { name: "Reaper Custom ( Tunershop )", price: 975000, category: "tunershop" },
  { name: "Sentinel XR ( Tunershop )", price: 316500, category: "tunershop" },
  { name: "Stratum Custom ( Tunershop )", price: 182500, category: "tunershop" },
  { name: "Sultan RS V8 ( Tunershop )", price: 402500, category: "tunershop" },
  { name: "Tahoma Lowrider ( Tunershop )", price: 221500, category: "tunershop" },
  { name: "Tampa Restomod ( Tunershop )", price: 182000, category: "tunershop" },
  { name: "Turismo Classic Custom ( Tunershop )", price: 445600, category: "tunershop" },
  { name: "Vigero Outlaw ( Tunershop )", price: 276500, category: "tunershop" },
  { name: "ZR350 Remaul ( Tunershop )", price: 367500, category: "tunershop" },
  { name: "Cheburek DriftSpec ( Tunershop )", price: 40000, category: "tunershop" },
  { name: "Euros DriftSpec ( Tunershop )", price: 232500, category: "tunershop" },
  { name: "FR36 DriftSpec ( Tunershop )", price: 139000, category: "tunershop" },
  { name: "Futo GTX DriftSpec ( Tunershop )", price: 77000, category: "tunershop" },
  { name: "Jester RR DriftSpec ( Tunershop )", price: 400000, category: "tunershop" },
  { name: "Remus DriftSpec ( Tunershop )", price: 111000, category: "tunershop" },
  { name: "Sentinel SG3 DriftSpec ( Tunershop )", price: 185000, category: "tunershop" },
  { name: "Tampa Drift DriftSpec ( Tunershop )", price: 300000, category: "tunershop" },
  { name: "Vorschlaghammer DriftSpec ( Tunershop )", price: 91500, category: "tunershop" },
  { name: "Yosemite DriftSpec ( Tunershop )", price: 115000, category: "tunershop" },
  { name: "ZR350 DriftSpec ( Tunershop )", price: 252500, category: "tunershop" },

];

// ---------------------- Références DOM ----------------------
const vehicleListEl = document.getElementById("vehicleList");
const selectedVehicleEl = document.getElementById("selectedVehicle");
const engineEl = document.getElementById("engineLevel");
const transmissionEl = document.getElementById("transmissionLevel");
const turboEl = document.getElementById("turbo");
const conditionEl = document.getElementById("condition");
const marginEl = document.getElementById("margin");
const buyPriceEl = document.getElementById("buyPrice");
const sellPriceEl = document.getElementById("sellPrice");
const profitEl = document.getElementById("profit");
const saveSaleBtn = document.getElementById("saveSale");
const salesHistoryTbody = document.querySelector("#salesHistory tbody");
const searchInput = document.getElementById("searchInput");

// ---------------------- Constantes ----------------------
const LS_KEY_STATE = "viktoria_last_state_v1";
const LS_KEY_SALES = "viktoria_sales_v1";
const CONDITION_COEFS = { "excellent": 0.95, "bon": 0.85, "moyen": 0.7, "mauvais": 0.5 };
const DEALER_FACTOR = 0.8; // Pour calcul du prix d'achat

// ---------------------- Fonctions utilitaires ----------------------
const fmt = n => (typeof n === "number" ? n.toLocaleString("en-US") : "-");
const toInt = v => parseInt(v || 0, 10);
const toFloat = v => parseFloat(v || 0);

// ---------------------- Génération liste véhicules ----------------------
let currentVehicle = null;
let lastComputed = null;

function buildVehicleList() {
  vehicleListEl.innerHTML = "";
  VEHICLES.forEach(v => {
    const li = document.createElement("li");
    li.className = "vehicle-item";
    li.dataset.name = v.name;
    li.dataset.category = v.category;
    li.innerHTML = `
      <span class="veh-name">${v.name}</span>
      <span class="veh-price">${fmt(v.price)} $</span>
    `;
    li.addEventListener("click", () => selectVehicle(v.name, li));
    vehicleListEl.appendChild(li);
  });
}

// ---------------------- Sélection véhicule ----------------------
function selectVehicle(name, liElement = null) {
  const v = VEHICLES.find(x => x.name === name);
  if (!v) return;
  currentVehicle = v;
  selectedVehicleEl.value = `${v.name} — ${fmt(v.price)} $`;

  // Active halo néon
  document.querySelectorAll("#vehicleList li").forEach(li => li.classList.remove("selected"));
  if (liElement) liElement.classList.add("selected");
  else {
    const found = [...document.querySelectorAll("#vehicleList li")].find(n => n.dataset.name === name);
    if (found) found.classList.add("selected");
  }

  saveState();
  compute();
}

// ---------------------- Calcul prix / bénéfice ----------------------
function compute() {
  if (!currentVehicle) return resetPrices();

  const prixNeuf = currentVehicle.price;
  const conditionKey = conditionEl.value || "bon";
  const baseCoef = CONDITION_COEFS[conditionKey] ?? 0.8;

  const engineLvl = Math.max(0, Math.min(5, toInt(engineEl.value)));
  const transLvl = Math.max(0, Math.min(5, toInt(transmissionEl.value)));
  const turboOn = (turboEl.value || "non").toLowerCase() === "oui";

  const bonus = engineLvl * 0.03 + transLvl * 0.02 + (turboOn ? 0.05 : 0);
  const totalCoef = Math.min(1.05, baseCoef + bonus);

  const buyPrice = Math.round(prixNeuf * totalCoef * DEALER_FACTOR);
  const marginPct = toFloat(marginEl.value) || 0;
  const sellPrice = Math.round(buyPrice * (1 + marginPct / 100));
  const profit = sellPrice - buyPrice;

  buyPriceEl.textContent = fmt(buyPrice);
  sellPriceEl.textContent = fmt(sellPrice);
  profitEl.textContent = fmt(profit);

  lastComputed = {
    vehicle: currentVehicle.name,
    buy: buyPrice,
    sell: sellPrice,
    profit,
    engine: engineLvl,
    transmission: transLvl,
    turbo: turboOn,
    condition: conditionKey,
    margin: marginPct,
    date: new Date().toISOString()
  };

  saveState();
}

function resetPrices() {
  buyPriceEl.textContent = "-";
  sellPriceEl.textContent = "-";
  profitEl.textContent = "-";
}

// ---------------------- LocalStorage ----------------------
function saveState() {
  try {
    const state = {
      selectedVehicle: currentVehicle ? currentVehicle.name : null,
      engine: toInt(engineEl.value),
      transmission: toInt(transmissionEl.value),
      turbo: (turboEl.value || "non").toLowerCase() === "oui",
      condition: conditionEl.value,
      margin: toFloat(marginEl.value)
    };
    localStorage.setItem(LS_KEY_STATE, JSON.stringify(state));
  } catch { }
}

function loadState() {
  try {
    const state = JSON.parse(localStorage.getItem(LS_KEY_STATE));
    if (!state) return;

    if (state.selectedVehicle) {
      const li = [...document.querySelectorAll("#vehicleList li")].find(n => n.dataset.name === state.selectedVehicle);
      if (li) selectVehicle(state.selectedVehicle, li);
    }

    if (typeof state.engine !== "undefined") engineEl.value = state.engine;
    if (typeof state.transmission !== "undefined") transmissionEl.value = state.transmission;
    if (typeof state.turbo !== "undefined") turboEl.value = state.turbo ? "oui" : "non";
    if (typeof state.condition !== "undefined") conditionEl.value = state.condition;
    if (typeof state.margin !== "undefined") marginEl.value = state.margin;
  } catch { }
}

// ---------------------- Historique ventes ----------------------
function loadSales() {
  try { return JSON.parse(localStorage.getItem(LS_KEY_SALES)) || []; } catch { return []; }
}
function saveSales(sales) { localStorage.setItem(LS_KEY_SALES, JSON.stringify(sales)); }

function renderSalesTable() {
  const sales = loadSales();
  salesHistoryTbody.innerHTML = "";
  sales.forEach((s, idx) => {
    const tr = document.createElement("tr");
    tr.innerHTML = `
      <td>${s.vehicle}</td>
      <td>${fmt(s.buy)} $</td>
      <td>${fmt(s.sell)} $</td>
      <td>${fmt(s.profit)} $</td>
      <td><button class="del-sale" data-idx="${idx}">✖</button></td>
    `;
    salesHistoryTbody.appendChild(tr);
  });

  document.querySelectorAll(".del-sale").forEach(btn => {
    btn.addEventListener("click", e => {
      const idx = parseInt(e.currentTarget.dataset.idx, 10);
      const s = loadSales();
      s.splice(idx, 1);
      saveSales(s);
      renderSalesTable();
    });
  });
}

saveSaleBtn.addEventListener("click", () => {
  if (!lastComputed) return alert("Fais d'abord un calcul avant d'enregistrer.");
  const sales = loadSales();
  sales.unshift(lastComputed);
  saveSales(sales);
  renderSalesTable();
  saveSaleBtn.textContent = "Enregistré ✓";
  setTimeout(() => saveSaleBtn.textContent = "💾 Enregistrer la vente", 1200);
});

// ---------------------- Barre de recherche ----------------------
searchInput.addEventListener("input", () => {
  const filter = searchInput.value.toLowerCase();
  document.querySelectorAll("#vehicleList li").forEach(li => {
    const name = li.dataset.name.toLowerCase();
    li.style.display = name.includes(filter) ? "flex" : "none";
  });
});

// ---------------------- Events calcul automatique ----------------------
[engineEl, transmissionEl, turboEl, conditionEl, marginEl].forEach(inp => {
  inp.addEventListener("input", compute);
});
marginEl.addEventListener("keydown", e => { if (e.key === "Enter") compute(); });

// ---------------------- Initialisation ----------------------
function init() {
  buildVehicleList();
  renderSalesTable();
  loadState();
  if (!currentVehicle && VEHICLES.length) {
    const firstLi = document.querySelector("#vehicleList li");
    if (firstLi) selectVehicle(VEHICLES[0].name, firstLi);
  }
  compute();
}

init();
